In [8]:
a = np.random.randn(10, 3)
print(a)
for j in range(10):
    s = abs(a[j][0] - 0.5)
    A = a[j][0]
    for i in range(1, 3):
        if (abs(a[j][i] - 0.5) < s):
            s = abs(a[j][i] - 0.5)
            A = a[j][i]
    print(A)

[[ 0.81642936 -0.62492997 -0.07404643]
 [-0.58199599 -0.35465618 -0.06955319]
 [ 1.1321548  -0.7781611  -1.40197131]
 [-0.13207513  0.61745377  0.40013387]
 [ 0.22453451  0.08818757  0.23329947]
 [-1.31894257 -0.19644174  1.68372234]
 [-0.56608164 -0.47055982  0.02093542]
 [ 2.55240942 -0.5827125   0.87047293]
 [ 1.82484224  0.68311256 -1.99672262]
 [-0.3566861  -0.65584139 -0.39604645]]
0.816429356957826
-0.0695531871233732
1.1321548006747786
0.40013386931945105
0.2332994714675692
-0.19644174451352026
0.020935419134568218
0.8704729260764618
0.6831125637123103
-0.35668609893541847


In [11]:
a = np.random.rand(6,6)
print(a)
for i in range(6):
    print(a[i].sum()/a[:,i].min())

[[0.5453273  0.06973517 0.83579972 0.25158366 0.34457856 0.14808282]
 [0.1196136  0.24628566 0.38358663 0.03345113 0.7372749  0.47477534]
 [0.21871135 0.01396712 0.92054232 0.81691156 0.12827832 0.07830276]
 [0.29923409 0.96634411 0.87941309 0.38343993 0.93305987 0.09525738]
 [0.56084005 0.71432753 0.45899023 0.53803089 0.83074595 0.00962572]
 [0.36458956 0.11499434 0.96081071 0.99521362 0.38816349 0.67996558]]
18.351652012989405
142.83456312972808
5.674633266225733
106.32672173272398
24.264117977981932
363.9975827065463


In [12]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
Max = 0
for i in range(1, len(x)):
    if (x[i-1] == 0):
        if (x[i] > Max):
            Max = x[i]
print(Max)

5


In [13]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
for j in i:
    x[j] = x[j] + 1.
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [23]:
def k_means(obs, k, iter, thresh):
    
    ch = 0 
    S = 0
    S_previous = thresh + 1
    k_or_guess = np.array(obs[:k])                                                                    
    check_where_obs_is = np.argmin(np.linalg.norm(obs - k_or_guess[:, None], axis = 2), axis = 0)  
    
    while (abs(S - S_previous) > thresh):
        
        ch = ch + 1
        if (ch > iter):
            break
        
        for K in range(k):
            k_or_guess[K] = np.mean(obs[check_where_obs_is == K], axis = 0) 
            
        check_where_obs_is = np.argmin(np.linalg.norm(obs - k_or_guess[:, None], axis = 2), axis = 0) 
        S_previous = S
        S = np.mean(np.linalg.norm(obs - k_or_guess[check_where_obs_is], axis = 1)) 
            
    return (check_where_obs_is, S)